version: '3.8'
services:
  bot:
    build: .
    container_name: emperie-classbot
    env_file:
      - ./.env 
    volumes:
      - ./app:/app  
      - /app/node_modules  
    restart: unless-stopped